export const SIGN_UP_REQUEST = 'SIGN_UP_REQUEST';
export const SIGN_IN_REQUEST = 'SIGN_IN_REQUEST';
export const GET_USER_DETAILS = 'GET_USER_DETAILS';
export const UPDATE_USER_DETAILS = 'UPDATE_USER_DETAILS';
